apiVersion: 1
datasources:
  - name: read-sensors
    type: frser-sqlite-datasource
    access: proxy
    orgId: 1
    isDefault: true
    jsonData:
      path: /var/lib/grafana/data/read-sensors.sqlite3
