{
 "title": "FlatSat2 Read Sensors",
 "time": { "from": "2026-01-15T23:59:52.308Z", "to": "2026-01-16T03:29:19.586Z" },
 "panels": [
  {
   "title": "LTC2983 Temperature Readings",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%Y-%m-%dT%H:%M:%fZ', timestamp) as time,\n  MAX(CASE WHEN sensorType = 'temp0' THEN value ELSE NULL END) as \"cold-junction\",\n  MAX(CASE WHEN sensorType = 'temp1' THEN value ELSE NULL END) as \"thermocouple-1\",\n  MAX(CASE WHEN sensorType = 'temp2' THEN value ELSE NULL END) as \"thermocouple-2\"\nFROM sensor_measurements\nWHERE \n  sensorName = 'ltc2983'\nGROUP BY time\nORDER BY time",
     "rawQueryText": "SELECT\n  strftime('%Y-%m-%dT%H:%M:%fZ', timestamp) as time,\n  MAX(CASE WHEN sensorType = 'temp0' THEN value ELSE NULL END) as \"cold-junction\",\n  MAX(CASE WHEN sensorType = 'temp1' THEN value ELSE NULL END) as \"thermocouple-1\",\n  MAX(CASE WHEN sensorType = 'temp2' THEN value ELSE NULL END) as \"thermocouple-2\"\nFROM sensor_measurements\nWHERE \n  sensorName = 'ltc2983'\nGROUP BY time\nORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Power Readings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%Y-%m-%dT%H:%M:%fZ', timestamp) as time,\n  MAX(CASE WHEN sensorName = 'h1-45_46' THEN value ELSE NULL END) as \"h1-45_46\",\n  MAX(CASE WHEN sensorName = 'h1-49_50' THEN value ELSE NULL END) as \"h1-49_50\",\n  MAX(CASE WHEN sensorName = 'h1-47_48' THEN value ELSE NULL END) as \"h1-47_48\",\n  MAX(CASE WHEN sensorName = 'h1-51_52' THEN value ELSE NULL END) as \"h1-51_52\",\n  MAX(CASE WHEN sensorName = 'h2-35_36' THEN value ELSE NULL END) as \"h2-35_36\",\n  MAX(CASE WHEN sensorName = 'h2-25_26' THEN value ELSE NULL END) as \"h2-25_26\",\n  MAX(CASE WHEN sensorName = 'h2-27_28' THEN value ELSE NULL END) as \"h2-27_28\"\nFROM sensor_measurements\nWHERE \n  measurementType = 'power'\nGROUP BY time\nORDER BY time",
     "rawQueryText": "SELECT\n  strftime('%Y-%m-%dT%H:%M:%fZ', timestamp) as time,\n  MAX(CASE WHEN sensorName = 'h1-45_46' THEN value ELSE NULL END) as \"h1-45_46\",\n  MAX(CASE WHEN sensorName = 'h1-49_50' THEN value ELSE NULL END) as \"h1-49_50\",\n  MAX(CASE WHEN sensorName = 'h1-47_48' THEN value ELSE NULL END) as \"h1-47_48\",\n  MAX(CASE WHEN sensorName = 'h1-51_52' THEN value ELSE NULL END) as \"h1-51_52\",\n  MAX(CASE WHEN sensorName = 'h2-35_36' THEN value ELSE NULL END) as \"h2-35_36\",\n  MAX(CASE WHEN sensorName = 'h2-25_26' THEN value ELSE NULL END) as \"h2-25_26\",\n  MAX(CASE WHEN sensorName = 'h2-27_28' THEN value ELSE NULL END) as \"h2-27_28\"\nFROM sensor_measurements\nWHERE \n  measurementType = 'power'\nGROUP BY time\nORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current Readings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%Y-%m-%dT%H:%M:%fZ', timestamp) as time,\n  MAX(CASE WHEN sensorName = 'h1-45_46' THEN value ELSE NULL END) as \"h1-45_46\",\n  MAX(CASE WHEN sensorName = 'h1-49_50' THEN value ELSE NULL END) as \"h1-49_50\",\n  MAX(CASE WHEN sensorName = 'h1-47_48' THEN value ELSE NULL END) as \"h1-47_48\",\n  MAX(CASE WHEN sensorName = 'h1-51_52' THEN value ELSE NULL END) as \"h1-51_52\",\n  MAX(CASE WHEN sensorName = 'h2-35_36' THEN value ELSE NULL END) as \"h2-35_36\",\n  MAX(CASE WHEN sensorName = 'h2-25_26' THEN value ELSE NULL END) as \"h2-25_26\",\n  MAX(CASE WHEN sensorName = 'h2-27_28' THEN value ELSE NULL END) as \"h2-27_28\"\nFROM sensor_measurements\nWHERE \n  measurementType = 'current'\nGROUP BY time\nORDER BY time",
     "rawQueryText": "SELECT\n  strftime('%Y-%m-%dT%H:%M:%fZ', timestamp) as time,\n  MAX(CASE WHEN sensorName = 'h1-45_46' THEN value ELSE NULL END) as \"h1-45_46\",\n  MAX(CASE WHEN sensorName = 'h1-49_50' THEN value ELSE NULL END) as \"h1-49_50\",\n  MAX(CASE WHEN sensorName = 'h1-47_48' THEN value ELSE NULL END) as \"h1-47_48\",\n  MAX(CASE WHEN sensorName = 'h1-51_52' THEN value ELSE NULL END) as \"h1-51_52\",\n  MAX(CASE WHEN sensorName = 'h2-35_36' THEN value ELSE NULL END) as \"h2-35_36\",\n  MAX(CASE WHEN sensorName = 'h2-25_26' THEN value ELSE NULL END) as \"h2-25_26\",\n  MAX(CASE WHEN sensorName = 'h2-27_28' THEN value ELSE NULL END) as \"h2-27_28\"\nFROM sensor_measurements\nWHERE \n  measurementType = 'current'\nGROUP BY time\nORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Voltage Readings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%Y-%m-%dT%H:%M:%fZ', timestamp) as time,\n  MAX(CASE WHEN sensorName = 'h1-45_46' THEN value ELSE NULL END) as \"h1-45_46\",\n  MAX(CASE WHEN sensorName = 'h1-49_50' THEN value ELSE NULL END) as \"h1-49_50\",\n  MAX(CASE WHEN sensorName = 'h1-47_48' THEN value ELSE NULL END) as \"h1-47_48\",\n  MAX(CASE WHEN sensorName = 'h1-51_52' THEN value ELSE NULL END) as \"h1-51_52\",\n  MAX(CASE WHEN sensorName = 'h2-35_36' THEN value ELSE NULL END) as \"h2-35_36\",\n  MAX(CASE WHEN sensorName = 'h2-25_26' THEN value ELSE NULL END) as \"h2-25_26\",\n  MAX(CASE WHEN sensorName = 'h2-27_28' THEN value ELSE NULL END) as \"h2-27_28\"\nFROM sensor_measurements\nWHERE \n  measurementType = 'voltage'\nGROUP BY time\nORDER BY time",
     "rawQueryText": "SELECT\n  strftime('%Y-%m-%dT%H:%M:%fZ', timestamp) as time,\n  MAX(CASE WHEN sensorName = 'h1-45_46' THEN value ELSE NULL END) as \"h1-45_46\",\n  MAX(CASE WHEN sensorName = 'h1-49_50' THEN value ELSE NULL END) as \"h1-49_50\",\n  MAX(CASE WHEN sensorName = 'h1-47_48' THEN value ELSE NULL END) as \"h1-47_48\",\n  MAX(CASE WHEN sensorName = 'h1-51_52' THEN value ELSE NULL END) as \"h1-51_52\",\n  MAX(CASE WHEN sensorName = 'h2-35_36' THEN value ELSE NULL END) as \"h2-35_36\",\n  MAX(CASE WHEN sensorName = 'h2-25_26' THEN value ELSE NULL END) as \"h2-25_26\",\n  MAX(CASE WHEN sensorName = 'h2-27_28' THEN value ELSE NULL END) as \"h2-27_28\"\nFROM sensor_measurements\nWHERE \n  measurementType = 'voltage'\nGROUP BY time\nORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}